#!/bin/bash
# Runs every scenario of one Feature, or of _global, each as its own invocation on fresh
# claude-data and gh-config volumes: the CLI removes containers but never volumes, and the
# volume names are fixed.
set -euo pipefail
id=$1
scenarios=test/$id/scenarios.json

# The CLI counts zero scenarios as a pass, and --filter is a substring match.
if ! jq -e 'length > 0' "$scenarios" >/dev/null; then
    echo "::error file=$scenarios::no scenarios"
    exit 1
fi
overlap=$(jq -r 'keys as $k | [$k[] as $a | $k[] as $b | select($a != $b and ($b | contains($a))) | "\($a) in \($b)"] | join(", ")' "$scenarios")
if [ -n "$overlap" ]; then
    echo "::error file=$scenarios::a scenario name is a substring of another, so --filter would run both: $overlap"
    exit 1
fi
# A new Feature mustn't skip the unsupported-image tests.
if [ "$id" = _global ]; then
    all=$(find src -mindepth 2 -maxdepth 2 -name devcontainer-feature.json -printf '%h\n' | cut -d/ -f2 | sort | jq -Rsc 'split("\n") | map(select(. != ""))')
    for name in alpine javascript-node; do
        declared=$(jq -c --arg s "$name" '.[$s].features // {} | keys | sort' "$scenarios")
        if [ "$declared" != "$all" ]; then
            echo "::error file=$scenarios::the $name scenario declares $declared, not every Feature: $all"
            exit 1
        fi
    done
fi

failed=()
for name in $(jq -r 'keys[]' "$scenarios"); do
    echo "::group::$id: $name"
    docker volume rm -f claude-data gh-config >/dev/null
    if [ "$id" = _global ]; then
        args=(--global-scenarios-only)
    else
        args=(-f "$id")
    fi
    node_modules/.bin/devcontainer features test "${args[@]}" --filter "$name" --skip-autogenerated . \
        || failed+=("$name")
    echo "::endgroup::"
done
if [ "${#failed[@]}" -gt 0 ]; then
    echo "::error::$id: failed scenarios: ${failed[*]}"
    exit 1
fi
