#!/bin/bash
# shellcheck source-path=SCRIPTDIR
# Usage: test-features.sh <id> [scenario]. Runs every scenario of one Feature
# or of _global, or only the one named, each as its own invocation on fresh
# claude-data, container-env, gh-config and liza-rebuild volumes: the CLI
# removes containers but never volumes, and the volume names are fixed. A
# scenario named *-rebuild then runs again on the volumes it left, as a
# rebuilt container would.
set -euo pipefail
# shellcheck source=feature_ids.sh
. "$(dirname "$0")/feature_ids.sh"
if [ "${CI:-}" != true ]; then
  echo "test-features.sh deletes the claude-data, container-env, gh-config" \
    "and liza-rebuild volumes; it runs only in CI" >&2
  exit 1
fi
volumes=(claude-data container-env gh-config liza-rebuild)
id=$1
only=${2:-}
scenarios=test/$id/scenarios.json

# The CLI counts zero scenarios as a pass, and --filter is a substring match.
if ! jq -e 'length > 0' "$scenarios" >/dev/null; then
  echo "::error file=$scenarios::no scenarios"
  exit 1
fi
overlap=$(jq -r 'keys as $k
  | [$k[] as $a | $k[] as $b | select($a != $b and ($b | contains($a)))
    | "\($a) in \($b)"]
  | join(", ")' "$scenarios")
if [ -n "$overlap" ]; then
  echo "::error file=$scenarios::a scenario name is a substring of another," \
    "so --filter would run both: $overlap"
  exit 1
fi
if [ -n "$only" ] \
  && ! jq -e --arg s "$only" 'has($s)' "$scenarios" >/dev/null; then
  echo "::error file=$scenarios::no scenario named $only"
  exit 1
fi
# A new Feature mustn't skip the image-coverage tests.
if [ "$id" = _global ]; then
  all=$(feature_ids | jq -Rsc 'split("\n") | map(select(. != ""))')
  for name in alpine javascript-node root-user; do
    declared=$(jq -c --arg s "$name" '.[$s].features // {} | keys | sort' \
      "$scenarios")
    if [ "$declared" != "$all" ]; then
      echo "::error file=$scenarios::the $name scenario declares $declared," \
        "not every Feature: $all"
      exit 1
    fi
  done
fi

if [ "$id" = _global ]; then
  args=(--global-scenarios-only)
else
  args=(-f "$id")
fi
run() { # scenario
  node_modules/.bin/devcontainer features test "${args[@]}" \
    --filter "$1" --skip-autogenerated --skip-duplicated .
}

failed=()
for name in $(jq -r --arg s "$only" 'keys[] | select($s == "" or . == $s)' \
  "$scenarios"); do
  echo "::group::$id: $name"
  # The CLI returns while Docker is still removing its test container, which
  # holds the volumes; the last try reports the error.
  for _ in $(seq 30); do
    docker volume rm -f "${volumes[@]}" >/dev/null 2>&1 && break
    sleep 2
  done
  docker volume rm -f "${volumes[@]}" >/dev/null
  if ! run "$name"; then
    failed+=("$name")
  elif [[ "$name" == *-rebuild ]]; then
    echo "$id: $name, pass 2 on the same volumes"
    # Without a persisting volume, pass 2 would pass as another pass 1.
    if ! run "$name" || ! docker run --rm -v liza-rebuild:/v alpine \
      test -e /v/.rebuild-pass2; then
      failed+=("$name (pass 2)")
    fi
  fi
  echo "::endgroup::"
done
if [ "${#failed[@]}" -gt 0 ]; then
  echo "::error::$id: failed scenarios: ${failed[*]}"
  exit 1
fi
